import React, { useState, useEffect, useMemo } from 'react';
import { Copy, Download, Eye, Code, CheckCircle, Save, Edit3, X } from 'lucide-react';
import Editor from '@monaco-editor/react';

const CodeViewer = ({ app, onCodeChange }) => {
  const [copied, setCopied] = useState(false);
  const [viewMode, setViewMode] = useState('formatted'); // 'formatted' or 'raw'
  const [localCode, setLocalCode] = useState(app?.code || '');
  const [isEditing, setIsEditing] = useState(false);
  const [hasChanges, setHasChanges] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    setLocalCode(app?.code || '');
    setIsEditing(false);
    setHasChanges(false);
    setSaved(false);
  }, [app?.code]);

  const handleCodeChange = useMemo(() => {
    return (value) => {
      if (!isEditing) return;
      setLocalCode(value);
      setHasChanges(value !== app?.code);
      setSaved(false);
    };
  }, [isEditing, app?.code]);

  const handleSave = () => {
    if (!hasChanges) return;
    onCodeChange?.(localCode);
    setSaved(true);
    setHasChanges(false);
    setIsEditing(false);
    setTimeout(() => setSaved(false), 2000);
  };

  const handleCancel = () => {
    setLocalCode(app?.code || '');
    setHasChanges(false);
    setIsEditing(false);
    setSaved(false);
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(localCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  const downloadCode = () => {
    const blob = new Blob([localCode], { type: 'text/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${app.appIdea.slice(0, 30).replace(/[^a-zA-Z0-9]/g, '-')}.jsx`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadFullProject = () => {
    const projectFiles = {
      'App.jsx': app.code,
      'package.json': JSON.stringify({
        name: app.appIdea.toLowerCase().replace(/[^a-zA-Z0-9]/g, '-'),
        version: '1.0.0',
        dependencies: {
          'react': '^18.2.0',
          'react-dom': '^18.2.0'
        },
        scripts: {
          'start': 'react-scripts start',
          'build': 'react-scripts build'
        }
      }, null, 2),
      'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${app.appIdea}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <div id="root"></div>
</body>
</html>`,
      'README.md': `# ${app.appIdea}

Generated by Morphic Web using ${app.model}

## Description
${app.appIdea}

## Generated on
${new Date(app.timestamp).toLocaleString()}

## Template Used
${app.template}

## To Run
1. Install dependencies: \`npm install\`
2. Start development server: \`npm start\`
`
    };

    // Create zip-like structure (simplified for demo)
    const projectContent = Object.entries(projectFiles)
      .map(([filename, content]) => `=== ${filename} ===\n${content}\n\n`)
      .join('');

    const blob = new Blob([projectContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${app.appIdea.slice(0, 30).replace(/[^a-zA-Z0-9]/g, '-')}-project.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!app) {
    return (
      <div className="text-center py-12">
        <div className="text-gray-400 mb-4">No code to display</div>
        <p className="text-gray-500">Generate an app first to view the code</p>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-white mb-2">
            <Code className="w-6 h-6 inline mr-2" />
            Editable Code
          </h2>
          <div className="flex items-center space-x-4 text-sm text-gray-300">
            <span>App: {app.appIdea}</span>
            <span>•</span>
            <span>Lines: {localCode.split('\n').length}</span>
            <span>•</span>
            <span>Size: {(new Blob([localCode]).size / 1024).toFixed(1)} KB</span>
          </div>
          <p className="text-xs text-gray-400 mt-1">
            ✏️ Edit code directly - changes auto-save and update the preview in real-time
          </p>
        </div>
        
        <div className="flex items-center space-x-3">
          {/* Save Status */}
          {saved && (
            <div className="flex items-center space-x-2 text-green-400 text-sm">
              <CheckCircle className="w-4 h-4" />
              <span>Saved & Updated Preview</span>
            </div>
          )}
          {!saved && isEditing && hasChanges && (
            <div className="flex items-center space-x-2 text-yellow-400 text-sm">
              <div className="w-2 h-2 bg-yellow-400 rounded-full animate-pulse"></div>
              <span>Unsaved edits</span>
            </div>
          )}

          {!isEditing ? (
            <button
              onClick={() => setIsEditing(true)}
              className="px-3 py-1 rounded-lg bg-white/10 hover:bg-white/20 text-sm text-white flex items-center gap-2 transition-colors"
            >
              <Edit3 className="w-4 h-4" />
              Edit Code
            </button>
          ) : (
            <div className="flex items-center space-x-2">
              <button
                onClick={handleSave}
                disabled={!hasChanges}
                className="px-3 py-1 rounded-lg bg-green-500 hover:bg-green-600 disabled:bg-green-500/40 text-sm text-white flex items-center gap-2 transition-colors"
              >
                <Save className="w-4 h-4" />
                Save Changes
              </button>
              <button
                onClick={handleCancel}
                className="px-3 py-1 rounded-lg bg-white/10 hover:bg-white/20 text-sm text-white flex items-center gap-2 transition-colors"
              >
                <X className="w-4 h-4" />
                Cancel
              </button>
            </div>
          )}

          {/* View Mode Toggle */}
          <div className="flex bg-white/10 rounded-lg p-1">
            <button
              onClick={() => setViewMode('formatted')}
              className={`px-3 py-1 rounded text-sm transition-colors ${
                viewMode === 'formatted'
                  ? 'bg-white/20 text-white'
                  : 'text-gray-300 hover:text-white'
              }`}
            >
              <Eye className="w-4 h-4 inline mr-1" />
              Formatted
            </button>
            <button
              onClick={() => setViewMode('raw')}
              className={`px-3 py-1 rounded text-sm transition-colors ${
                viewMode === 'raw'
                  ? 'bg-white/20 text-white'
                  : 'text-gray-300 hover:text-white'
              }`}
            >
              <Code className="w-4 h-4 inline mr-1" />
              Raw
            </button>
          </div>

          <button
            onClick={copyToClipboard}
            className="px-4 py-2 bg-white/10 hover:bg-white/20 text-white rounded-lg transition-colors flex items-center space-x-2"
          >
            {copied ? <CheckCircle className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>
          
          <button
            onClick={downloadCode}
            className="px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition-colors flex items-center space-x-2"
          >
            <Download className="w-4 h-4" />
            <span>Download JSX</span>
          </button>

          <button
            onClick={downloadFullProject}
            className="px-4 py-2 bg-green-500 hover:bg-green-600 text-white rounded-lg transition-colors flex items-center space-x-2"
          >
            <Download className="w-4 h-4" />
            <span>Full Project</span>
          </button>
        </div>
      </div>

      {/* Code Display */}
      <div className="bg-white/5 backdrop-blur-md rounded-2xl border border-white/20 overflow-hidden">
        <div className="bg-white/10 px-6 py-3 border-b border-white/20">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="flex space-x-2">
                <div className="w-3 h-3 bg-red-400 rounded-full"></div>
                <div className="w-3 h-3 bg-yellow-400 rounded-full"></div>
                <div className="w-3 h-3 bg-green-400 rounded-full"></div>
              </div>
              <span className="text-sm text-gray-300">App.jsx</span>
            </div>
            <div className="text-xs text-gray-400">
              Generated with {app.model}
            </div>
          </div>
        </div>

        <div style={{ height: '70vh' }}>
          {viewMode === 'formatted' ? (
            <Editor
              defaultLanguage="javascript"
              value={localCode}
              onChange={handleCodeChange}
              theme="vs-dark"
              options={{
                readOnly: !isEditing,
                fontSize: 14,
                lineNumbers: 'on',
                minimap: { enabled: true },
                scrollBeyondLastLine: false,
                wordWrap: 'on',
                folding: true,
                selectOnLineNumbers: true,
                automaticLayout: true
              }}
            />
          ) : (
            <pre className="h-full overflow-auto p-6 text-sm text-gray-300 font-mono bg-gray-900">
              <code>{localCode}</code>
            </pre>
          )}
        </div>
      </div>

      {/* Code Analysis */}
      <div className="mt-6 grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-white/10 backdrop-blur-md rounded-lg border border-white/20 p-4">
          <h4 className="font-semibold text-white mb-2">Components</h4>
          <p className="text-gray-300 text-sm">
            {(app.code.match(/function\s+\w+|const\s+\w+\s*=/g) || []).length} detected
          </p>
        </div>
        
        <div className="bg-white/10 backdrop-blur-md rounded-lg border border-white/20 p-4">
          <h4 className="font-semibold text-white mb-2">Hooks Used</h4>
          <p className="text-gray-300 text-sm">
            {(app.code.match(/use\w+/g) || []).length} hooks
          </p>
        </div>
        
        <div className="bg-white/10 backdrop-blur-md rounded-lg border border-white/20 p-4">
          <h4 className="font-semibold text-white mb-2">Imports</h4>
          <p className="text-gray-300 text-sm">
            {(app.code.match(/import\s+/g) || []).length} statements
          </p>
        </div>
        
        <div className="bg-white/10 backdrop-blur-md rounded-lg border border-white/20 p-4">
          <h4 className="font-semibold text-white mb-2">JSX Elements</h4>
          <p className="text-gray-300 text-sm">
            {(app.code.match(/<\w+/g) || []).length} elements
          </p>
        </div>
      </div>

      {/* Generation Details */}
      <div className="mt-6 bg-white/10 backdrop-blur-md rounded-lg border border-white/20 p-6">
        <h3 className="text-lg font-semibold text-white mb-4">Generation Details</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <h4 className="font-medium text-white mb-2">Original Prompt</h4>
            <div className="bg-white/5 rounded-lg p-3 text-sm text-gray-300 font-mono max-h-32 overflow-y-auto">
              {app.prompt}
            </div>
          </div>
          <div>
            <h4 className="font-medium text-white mb-2">Metadata</h4>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-gray-400">Model:</span>
                <span className="text-gray-300">{app.model}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-400">Template:</span>
                <span className="text-gray-300">{app.template}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-400">Generated:</span>
                <span className="text-gray-300">{new Date(app.timestamp).toLocaleString()}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-400">Status:</span>
                <span className={app.isWorking ? 'text-green-400' : 'text-yellow-400'}>
                  {app.isWorking ? 'Working' : 'Fallback'}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CodeViewer;
